import type { Metadata } from 'next'
import { Tinos } from 'next/font/google'
import './globals.css'

const tinos = Tinos({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={tinos.className}>{children}</body>
    </html>
  )
}
